### ISSUE TITLE
Bogus error logs (with stack traces) when deserializing ViewModels extending from abstract classes

### ISSUE THREAD

**Issue by Dretch** [dd4t/dd4t-2-java#102]
My application logs are full of errors matching the pattern below, but functionally everything works as expected:

```
java.lang.InstantiationException: null
	at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.dd4t.databind.builder.json.JsonDataBinder.buildModel(JsonDataBinder.java:210)
	at org.dd4t.databind.builder.json.JsonModelConverter.buildModelForField(JsonModelConverter.java:373)
	at org.dd4t.databind.builder.json.JsonModelConverter.checkTypeAndBuildModel(JsonModelConverter.java:359)
	at org.dd4t.databind.builder.json.JsonModelConverter.deserializeAndBuildModels(JsonModelConverter.java:297)
	at org.dd4t.databind.builder.json.JsonModelConverter.buildField(JsonModelConverter.java:254)
	at org.dd4t.databind.builder.json.JsonModelConverter.buildModelProperties(JsonModelConverter.java:141)
	at org.dd4t.databind.builder.json.JsonModelConverter.convertSource(JsonModelConverter.java:110)
	at org.dd4t.databind.builder.json.JsonDataBinder.buildModel(JsonDataBinder.java:217)
	at org.dd4t.databind.builder.json.JsonModelConverter.getBaseViewModel(JsonModelConverter.java:419)
	at org.dd4t.databind.builder.json.JsonModelConverter.buildModelForField(JsonModelConverter.java:395)
	at org.dd4t.databind.builder.json.JsonModelConverter.checkTypeAndBuildModel(JsonModelConverter.java:359)
	at org.dd4t.databind.builder.json.JsonModelConverter.deserializeAndBuildModels(JsonModelConverter.java:279)
	at org.dd4t.databind.builder.json.JsonModelConverter.buildField(JsonModelConverter.java:254)
	at org.dd4t.databind.builder.json.JsonModelConverter.buildModelProperties(JsonModelConverter.java:141)
	at org.dd4t.databind.builder.json.JsonModelConverter.convertSource(JsonModelConverter.java:110)
	at org.dd4t.databind.builder.json.JsonDataBinder.buildModel(JsonDataBinder.java:217)
	at org.dd4t.databind.builder.json.JsonDataBinder.buildModels(JsonDataBinder.java:172)
	at org.dd4t.databind.serializers.json.ComponentPresentationDeserializer.renderComponentData(ComponentPresentationDeserializer.java:166)
	at org.dd4t.databind.serializers.json.ComponentPresentationDeserializer.deserialize(ComponentPresentationDeserializer.java:137)
	at org.dd4t.databind.serializers.json.ComponentPresentationDeserializer.deserialize(ComponentPresentationDeserializer.java:53)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:285)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:519)
	at com.fasterxml.jackson.module.afterburner.deser.SettableObjectMethodProperty.deserializeAndSet(SettableObjectMethodProperty.java:47)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:251)
	at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:155)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2992)
	at org.dd4t.databind.builder.json.JsonDataBinder.buildPage(JsonDataBinder.java:83)
	at org.dd4t.core.factories.impl.PageFactoryImpl.deserialize(PageFactoryImpl.java:411)
	at org.dd4t.core.factories.impl.PageFactoryImpl.producePage(PageFactoryImpl.java:384)
	at org.dd4t.core.factories.impl.PageFactoryImpl.findPageByUrl(PageFactoryImpl.java:360)
	at org.dd4t.core.factories.impl.PageFactoryImpl.findPageByUrl(PageFactoryImpl.java:72)
	... the rest of the stack frames are application specific
```

Strangely, the call to `org.dd4t.databind.builder.json.JsonDataBinder.buildModel` which logs the error appears to be redundant - the return value is not used. The apparently redundant code can be found here:

https://github.com/dd4t/dd4t-2-java/blob/9d9f6f6e09b040edf63f92b8e49269990c5df726/dd4t-databind/src/main/java/org/dd4t/databind/builder/json/JsonModelConverter.java#L373

Can the redundant code simply be removed?

**Comment by RaimondKempees** [comment]
Fixed on Dev. Must have been a bad merge or something.

**Comment by Dretch** [comment]
Awesome. Thanks @RaimondKempees
