### ISSUE TITLE
Rendering XPM comment for a null field throws exception in thymeleaf tag xpm:field

### ISSUE THREAD

**Issue by anindita-pal** [dd4t/dd4t-2-java#86]
In our thymeleaf view we do not do null check on text/String field, because thymeleaf tag <th:utext> and <th:text> will not display anything when its null. But <xpm:field> tag throws exception which break the entire page at view time.The XpmFieldProcessor should not throw exception, instead just log the error and not render the XPM comment for that field.

Exception thrown:
Caused By: java.lang.IllegalArgumentException: Unknown field='descriptionLong' in [featureImageSizeTwo, commonContent, chapterTitle]
        at org.dd4t.databind.viewmodel.base.TridionViewModelBase.getXPath(TridionViewModelBase.java:117)
        at org.dd4t.thymeleaf.dialect.processor.xpm.XpmFieldProcessor.doProcess(XpmFieldProcessor.java:86)
        at org.thymeleaf.processor.element.AbstractElementTagProcessor.process(AbstractElementTagProcessor.java:95)
        at org.thymeleaf.util.ProcessorConfigurationUtils$ElementTagProcessorWrapper.process(ProcessorConfigurationUtils.java:633)
        at org.thymeleaf.engine.ProcessorTemplateHandler.handleStandaloneElement(ProcessorTemplateHandler.java:918)

**Comment by RaimondKempees** [comment]
Fixed in 2.0.10 and 2.1.0-beta2
